logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty.http.client.HttpClient: DEBUG
spring:
  jpa.hibernate.ddl-auto: update
  freemarker.suffix: .html
  h2.console.enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-35-173-94-156.compute-1.amazonaws.com:5432/d896fdb9bj8p8n
    username: kiksbahwhtejqj
    password: 42b0fb232319fbb93ec02bd73a49f792611b7582dd41afc869a931a2a5011e5b
  security:
    oauth2:
      client:
        provider:
          twitch:
            authorization-uri: https://id.twitch.tv/oauth2/authorize
            token-uri: https://id.twitch.tv/oauth2/token
            user-info-uri: https://id.twitch.tv/oauth2/userinfo
            user-name-attribute: preferred_username
        registration:
          twitch:
            client-id: p787xc47yt0vokvgpq0ka6efhyjts3
            client-secret: allru9wy9kss4nhrpc5ssn8s0cqakc
            client-authentication-method: post
            redirect-uri: "{baseUrl}/login/oauth2/code/twitch"
            provider: twitch
            authorization-grant-type: authorization_code
            scope:
              - "user:read:email"
              - "clips:edit"
server:
  servlet:
    session.timeout: 7d

app-access-token: 6c3kfri8ik547s04l6rpjnzkbcn4j5